name: 'Discord Courier'
description: 'Post and update Discord messages via your Discord Bot'
inputs:
  discord_token:
    description: Discord Bot Token for Authentication
    required: true
  post_file:
    description: Path to the file containing the post
    required: true
  discord_channel:
    description: Discord Channel ID
    required: true
  discord_message:
    description: Existing message ID to update (must be owned by the bot user)
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
